version: '2.4'
services: 
  webapp: 
    image: ${WEBAPP_IMAGE}
    ports: 
      - '8080:3000'
    env_file:
      - .env
    restart: always
  api:
    image: ${API_IMAGE}
    ports:
      - '4040:5000'
    env_file:
      - .env
    restart: always
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports: 
      - '27017:27017'